name: Build and deploy Python app to Azure Web App - fluxo-api

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Instalar dependências dentro da pasta serverapp
      - name: Instalar dependências
        working-directory: ./serverapp
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Opcional: rodar testes aqui se quiser

      # Deploy para o App Service
      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: fluxo-api
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_XXXX }}
          package: ./serverapp
